PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX aopo: <http://aopkb.org/aop_ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?upstream ?downstream ?upstreamTitle ?downstreamTitle ?description ?plausibility ?empiricalSupport ?quantitativeUnderstanding ?gene ?aop ?aopTitle ?created ?modified ?reference ?referenceLabel ?referenceText
WHERE {{
  BIND(<{ker_iri}> AS ?ker)
  OPTIONAL {{
    ?ker aopo:has_upstream_key_event ?upstream ;
         aopo:has_downstream_key_event ?downstream .
    OPTIONAL {{ ?upstream dc:title ?upstreamTitle }}
    OPTIONAL {{ ?downstream dc:title ?downstreamTitle }}
  }}
  OPTIONAL {{ ?ker dc:description ?description }}
  OPTIONAL {{ ?ker <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C80263> ?plausibility }}
  OPTIONAL {{ ?ker <http://edamontology.org/data_2042> ?empiricalSupport }}
  OPTIONAL {{ ?ker <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C71478> ?quantitativeUnderstanding }}
  OPTIONAL {{ ?ker <http://edamontology.org/data_1025> ?gene }}
  OPTIONAL {{
    ?ker dcterms:isPartOf ?aop .
    OPTIONAL {{ ?aop dc:title ?aopTitle }}
  }}
  OPTIONAL {{ ?ker dcterms:created ?created }}
  OPTIONAL {{ ?ker dcterms:modified ?modified }}
  OPTIONAL {{
    ?ker dcterms:references ?reference .
    OPTIONAL {{ ?reference dc:title ?referenceLabel }}
    OPTIONAL {{ ?reference rdfs:label ?referenceLabel }}
  }}
  OPTIONAL {{ ?ker dcterms:bibliographicCitation ?referenceText }}
}}
