PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX aopo: <http://aopkb.org/aop_ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?title ?shortName ?status ?abstract
WHERE {{
  BIND(<{aop_iri}> AS ?aop)
  ?aop rdfs:label ?title .
  OPTIONAL {{ ?aop skos:altLabel ?shortName }}
  OPTIONAL {{ ?aop aopo:has_status ?status }}
  OPTIONAL {{ ?aop dc:description ?abstract }}
}}
LIMIT 1
