PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX aopo: <http://aopkb.org/aop_ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?ke ?label ?eventType
WHERE {{
  <{aop_iri}> aopo:has_key_event ?ke .
  ?ke dc:title ?label .
  OPTIONAL {{ ?ke aopo:has_event_type ?eventType }}
}}
ORDER BY LCASE(?label)
