PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX aopo: <http://aopkb.org/aop_ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?ker ?upstream ?downstream ?plausibility ?status
WHERE {{
  <{aop_iri}> aopo:has_key_event_relationship ?ker .
  ?ker aopo:has_upstream_key_event ?upstream ;
       aopo:has_downstream_key_event ?downstream .
  OPTIONAL {{ ?ker aopo:has_biological_plausibility ?plausibility }}
  OPTIONAL {{ ?ker aopo:has_status ?status }}
}}
ORDER BY LCASE(STR(?ker))
