PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX aopo: <http://aopkb.org/aop_ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?aop ?title ?shortName
WHERE {{
  ?aop a aopo:AdverseOutcomePathway ;
       dc:title ?title .
  OPTIONAL {{ ?aop skos:altLabel ?shortName }}
  {filter_clause}
}}
ORDER BY LCASE(?title)
LIMIT {limit}
