PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX aopo: <http://aopkb.org/aop-ontology#>

SELECT ?aop ?title ?shortName
WHERE {{
  ?aop a aopo:AdverseOutcomePathway ;
       dcterms:title ?title .
  OPTIONAL {{ ?aop aopo:has_short_name ?shortName }}
  {filter_clause}
}}
ORDER BY LCASE(?title)
LIMIT {limit}
