PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX aopo: <http://aopkb.org/aop_ontology#>

SELECT DISTINCT ?stressor ?stressorLabel ?chemicalEntity
WHERE {{
  ?stressor dcterms:isPartOf <{aop_iri}> ;
            aopo:has_chemical_entity ?chemicalEntity .
  OPTIONAL {{ ?stressor dc:title ?stressorLabel }}
}}
ORDER BY LCASE(COALESCE(?stressorLabel, STR(?stressor)))
LIMIT 100
