PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX aopo: <http://aopkb.org/aop_ontology#>
PREFIX ncit: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>

SELECT DISTINCT ?aop ?title ?stressId
WHERE {{
  ?stressId a ncit:C54571 .
  
  {{
     FILTER(STRLEN("{name}") > 0)
     ?stressId dc:title ?stressorLabel .
     FILTER(CONTAINS(LCASE(?stressorLabel), LCASE("{name}")))
  }}
  UNION
  {{
     FILTER(STRLEN("{cas}") > 0)
     ?stressId aopo:has_chemical_entity <https://identifiers.org/cas/{cas}> .
  }}

  ?stressId dcterms:isPartOf ?aop .
  ?aop a aopo:AdverseOutcomePathway ;
       dc:title ?title .
}}
LIMIT 50
